export const GET_SHOW_WITH_EPISODES = 'GET_SHOW_WITH_EPISODES';
export const GET_SHOW_WITH_EPISODES_SUCCESS = 'GET_SHOW_WITH_EPISODES_SUCCESS';
export const GET_SHOW_WITH_EPISODES_FAIL = 'GET_SHOW_WITH_EPISODES_FAIL';

export const GET_EPISODES_DETAILS = 'GET_EPISODES_DETAILS';
export const GET_EPISODES_DETAILS_SUCCESS = 'GET_EPISODES_DETAILS_SUCCESS';
export const GET_EPISODES_DETAILS_FAIL = 'GET_EPISODES_DETAILS_FAIL';
